# Site settings
title: Leandro Ostera
subtitle: a Î»-man in a von Neumann world
email: leandro@ostera.io
description: | # this means to ignore newlines until "baseurl:"
  Software Developer, Spotify <br>
  Former Software Developer, Klarna <br>
  Former Software Developer, CleverTech

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ostera.io" # the base hostname & protocol for your site
github_username:  ostera

# Build settings
markdown: kramdown
