# Site settings
title: Leandro Ostera
subtitle: Arranger of bits, emitter of sounds. My opinions are my own.
email: leandro@ostera.io
description: | # this means to ignore newlines until "baseurl:"
  Software Developer, Klarna <br>
  Former Director of Engineering, Laterally <br>
  Former Web Engineer, CleverTech

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ostera.io" # the base hostname & protocol for your site
github_username:  ostera

# Build settings
markdown: kramdown
