# Site settings
title: Leandro Ostera 
email: leandro@ostera.io
description: > # this means to ignore newlines until "baseurl:"
  CTO at MacroLab<br> 
  Former Director of Engineer @ Lateral.ly<br>
  Former Web Engineer @ Clevertech.biz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ostera.io" # the base hostname & protocol for your site
github_username:  ostera

# Build settings
markdown: kramdown
