# Site settings
title: Leandro Ostera 
email: leandro@ostera.me
description: > # this means to ignore newlines until "baseurl:"
  Woot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ostera.me" # the base hostname & protocol for your site
twitter_username: leostera
github_username:  ostera

# Build settings
markdown: kramdown
